"""Sprint 7: Modelos de WiFi, Peticiones y Calificacion

Revision ID: 088a648f6ddd
Revises: 61064e6968be
Create Date: 2025-10-21 11:46:43.086646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '088a648f6ddd'
down_revision = '61064e6968be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_wifi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('ssid_2g', sa.String(length=64), nullable=False),
    sa.Column('clave_2g', sa.String(length=128), nullable=False),
    sa.Column('ssid_5g', sa.String(length=64), nullable=True),
    sa.Column('clave_5g', sa.String(length=128), nullable=True),
    sa.Column('encriptacion', sa.String(length=20), nullable=True),
    sa.Column('nro_serie_equipo', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id')
    )
    op.create_table('peticion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tipo_peticion', sa.String(length=50), nullable=False),
    sa.Column('detalle_plan', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_gestion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calificacion_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('technical_visit_id', sa.Integer(), nullable=False),
    sa.Column('puntuacion', sa.Integer(), nullable=False),
    sa.Column('satisfaccion_valida', sa.Boolean(), nullable=True),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('fecha_calificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['technical_visit_id'], ['technical_visit.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('technical_visit_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calificacion_servicio')
    op.drop_table('peticion')
    op.drop_table('configuracion_wifi')
    # ### end Alembic commands ###
