"""Implementacion de campos status y ref_externa en Invoice

Revision ID: 62c9698ea6dd
Revises: f093041dd02b
Create Date: 2025-11-15 17:19:00.924040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62c9698ea6dd'
down_revision = 'f093041dd02b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('external_reference', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('external_reference')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
