"""empty message

Revision ID: 730659f836f6
Revises: 088a648f6ddd
Create Date: 2025-11-15 15:33:14.659671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730659f836f6'
down_revision = '088a648f6ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('mfa_enable', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('mfa_enable')
        batch_op.drop_column('totp_secret')

    # ### end Alembic commands ###
