"""Aumentar tamaño de password a 256

Revision ID: 912e6f45336e
Revises: 62c9698ea6dd
Create Date: 2025-12-09 17:37:56.338176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '912e6f45336e'
down_revision = '62c9698ea6dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False)

    # ### end Alembic commands ###
